### ISSUE TITLE
Webpack 5: DeprecationWarning: Compilation.assets will be frozen in future

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/add-asset-webpack-plugin#5]
Webpack 5 complains quite loudly about this plugin:

````
(node:15826) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
  Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
  Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at node_modules/add-asset-webpack-plugin/index.js:13:38
    at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.emitAssets (node_modules/webpack/lib/Compiler.js:763:19)
    at node_modules/webpack/lib/Watching.js:80:21
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
````

**Comment by sindresorhus** [comment]
I don't use this anymore, so I don't have the motivation to figure out what needs to be done to upgrade. I'm marking this as "help welcome".

**Comment by silverwind** [comment]
Maybe I'll look into it. The necessary changes will probably be of breaking nature because the recommended API isn't there in Webpack 4, so it'd support Webpack 5 only.
